---
:authentication:
  :method: OAuth2
  :oauth2_client_id: ENV['adwords_oauth2_client_id']
  :oauth2_client_secret: ENV['adwords_oauth2_client_secret']
  :developer_token: ENV['adwords_developer_token']
  :client_customer_id: ENV['adwords_client_customer_id']
  :user_agent: "rerum"
  :oauth2_token:
    :access_token: ENV['adwords_oauth2_access_token']
    :refresh_token: ya29.Ci9XA6O_v94Nb6KYuEmkfgCmtR57CX3_QZ4k-Ulqa0memKiUS8qfRwIU1aY-49fhzA
    :issued_at: 2016-09-06 20:26:19.967783000 -04:00
    :expires_in: 3600
    :id_token: 
:service:
  :environment: PRODUCTION
:connection:
  :enable_gzip: false
:library:
  :log_level: INFO
